CREATE TABLE storme.user_ppid (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100),
    middle_name VARCHAR(100),
    last_name VARCHAR(100),
    preferred_name VARCHAR(100),
    gender VARCHAR(50),
    date_of_birth DATE,
    profile_picture_url VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    secondary_email VARCHAR(255),
    phone_number VARCHAR(20),
    alternate_phone_number VARCHAR(20),
    preferred_contact_method VARCHAR(50),
    address_line_1 VARCHAR(255),
    address_line_2 VARCHAR(255),
    city VARCHAR(100),
    state_province VARCHAR(50),
    postal_code VARCHAR(20),
    country VARCHAR(50),
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    security_questions JSONB,  -- JSON format for flexibility
    government_id_type VARCHAR(50),
    government_id_number VARCHAR(100) UNIQUE,
    date_of_account_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_timestamp TIMESTAMP,
    account_status VARCHAR(50) CHECK (account_status IN ('active', 'inactive', 'suspended', 'deleted')),
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    two_factor_method VARCHAR(50),
    school VARCHAR(255),
    student_id VARCHAR(50) UNIQUE,
    created_by INT,
    updated_by INT,
    gdpr_consent BOOLEAN DEFAULT FALSE,
    ccpa_consent BOOLEAN DEFAULT FALSE,
    terms_acceptance_date TIMESTAMP,
    marketing_opt_in BOOLEAN DEFAULT FALSE,
    data_retention_expiration DATE
);